from app.executor.browser import BrowserExecutor
browser = BrowserExecutor(headless=False)
browser.open(r"C:\Users\swastik\Desktop\visionFlow\demo.html")
browser.wait()
browser.screenshot("screenshots/test.png")
browser.type_by_placeholder("Email", "abc@test.com")
browser.type_by_placeholder("Password", "123456")
browser.click_by_text("Login")
browser.screenshot("screenshots/afterlogin.png")
browser.close()
